server:
  port: 8001

spring:
  application:
    name: arbi-tech-restaurant-order
  datasource:
    url: jdbc:mysql://localhost:3306/arbi-tech-restaurant-order
    username: root
    password: e@113177
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
