server:
  port: 8002

spring:
  application:
    name: abri-tech-restaurant-order
  datasource:
    url: jdbc:mysql://mysql-62449-0.cloudclusters.net:10535/arbi-tech-restaurant-order
    username: admin
    password: hMyO7LE2
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
